name: Optimize Images

on:
  push:
    branches:
      - main
    paths:
      - 'public/**'
  workflow_dispatch:

jobs:
  optimize:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Optimize images in public/
        uses: calibreapp/image-actions@v1
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          compressOnly: true
          jpegQuality: 82
          pngQuality: 80
          ignorePaths: 'node_modules/**,dist/**'

      - name: Commit optimized images
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'chore(images): optimize assets in public/'
          file_pattern: public/**
